#!/bin/bash

LOCAL_PORT=1025

oc port-forward svc/maildev-smtp ${LOCAL_PORT}:25 &
PID=$!

echo -n "waiting for listener..."
while : ; do
  nc -w 1 localhost $LOCAL_PORT
  if [ $? -eq 0 ]; then
    echo "done"
    break
  else
    echo -n "."
    sleep 1
  fi
done

(
  echo "HELO test.example.com\r"
  sleep 3
  echo "MAIL FROM:<user1@test.com>\r"
  sleep 3
  echo "RCPT TO:<user2@test.com>\r"
  sleep 3
  echo "DATA\r"
  sleep 3
  echo "Date: $(date)\r"
  echo "From: User 1 <user1@test.com>\r"
  echo "Subject: Test Message\r"
  echo "To: User 2 <user2@test.com>\r"
  echo "\r"
  echo "Hello, this is a test.\r"
  echo ".\r"
  sleep 3
) | nc localhost $LOCAL_PORT

kill $PID
