apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: send-email
  generateName: send-email-
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      # Code copied from https://docs.python.org/3/library/smtplib.html
      - command:
        - /bin/bash
        - -c
        - |
          cat <<EOF | python3
          import smtplib

          fromaddr="user1@example.com"
          toaddr="user2@example.com"
          smtpserver = "maildev-smtp"

          msg = ("From: %s\r\nTo: %s\r\nSubject: Test Message\r\n\r\nHello, this is a test\r\n" % (fromaddr, toaddr))
          server = smtplib.SMTP(smtpserver)
          server.set_debuglevel(1)
          server.sendmail(fromaddr, toaddr, msg)
          server.quit()
          EOF

        image: registry.access.redhat.com/ubi8/python-38:1-86
        name: send-email
        resources: {}
      restartPolicy: Never
status: {}
