apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: send-email
  generateName: send-email-
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      # Code copied from https://docs.python.org/3/library/smtplib.html
      - env:
        - name: FROM
          value: "user1@example.com"
        - name: TO
          value: "user2@example.com"
        - name: SUBJECT
          value: "Test Message"
        - name: BODY
          value: "Hello, this is a test"
        - name: SMTPSERVER
          value: "maildev-smtp"
        command:
        - /bin/bash
        - -c
        - |
          cat <<EOF | python3
          import os
          import smtplib

          fromaddr=os.getenv('FROM')
          toaddr=os.getenv('TO')
          subject=os.getenv('SUBJECT')
          body=os.getenv('BODY')
          smtpserver = os.getenv('SMTPSERVER')

          msg = ("From: %s\r\nTo: %s\r\nSubject: %s\r\n\r\n%s\r\n" % (fromaddr, toaddr, subject, body))
          server = smtplib.SMTP(smtpserver)
          server.set_debuglevel(1)
          server.sendmail(fromaddr, toaddr, msg)
          server.quit()
          EOF

        image: registry.access.redhat.com/ubi8/python-38:1-86
        name: send-email
        resources: {}
      restartPolicy: Never
status: {}
